language: python
node_js:
  - "0.12"

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

branches:
  except:
  - master

addons:
  apt:
    packages:
    - nodejs
    - gulp
    - npm

install:
- locale -a
- gem install sass
- nvm install "v0.12.9"
- nvm use "v0.12.9"
- npm install
- pip install pip wheel -U
- pip install -r requirements.txt
script:
- bash -c "echo \"$TRAVIS_BRANCH\""
- bash -c "if [ \"$TRAVIS_BRANCH\" == \"production\" ]; then echo 'Publish'; make publish github; else echo 'Regenerate only'; make html; fi";
env:
  secure: "CkF40rXI+7Fcq0vG5A2u4mEFNKlNAnfA3zcvFRIq+YszwCZ66m9dNSVeWfc83NdR4m6SIXS/CH6MJ9+/d2d1ZkRyqVzKpOwGZHkvnnQtX/wnQ1nWKtlbRPPrADW/6kpfeA7U+Z5jYA9xPHWawlMoxoLTgjYaCNbEcU9KUCK0D3Oh9YqnO/lC6W2KtAxw4tZe8PIpw0YITq069yAbMvD9BCoYEYa/IrxhMeX01ohWI4G1nFt/k+Sewk7V/uB5llw4LQj5U2v3DFoBPHwbcABI8W8thN6+A8Ib9UwesjhRsK2rCSfhMybRhb9gsN8WHcjXy2RvB+xKWLYIP0uayGWrVm3ae4msPOQ04DTX2mBJ46DYlKZbX/wUUAWKfgU9L5Qb6YL7uvliChtmhFBmhyDEmtsr3AISgxGyBGmUVH/3VfN+F28P17hVHEWcXQlfnM9cj2kufrH3f9HZb3Ha7jUuRS8zvXnruKLgV/3h1T7c6VAjf+lf0OOIOps7+SHRGJxeByGRaX39YsULDNGPX/aukGBA/MLotbBOVFSgA+2Th/Wemg1bh09DbC1xXTReIBuwofTit+hcMuEg89SxYW43bWQn8xFlhP3Bzmvu7WJc3rfkOflLwPui8zMJHDHgZJn1xvTeLv55mPa9XkZMkfuQW28y+WN1XKuB5ER/rLetL1M="
post_install: 
- rm $HOME/.cache/pip/log/*
